
//! ========== NODE INTERVIEW QNA ==========

//^ what is nodejs ?
//NODEJS IS JAVASCRIPT  RUNTIME BUILT ON CHROME'S V8 ENGINE FOR EXECUTING JAVASCRIPT ON SERVER SIDE.

//^ IS NODEJS IS SINGLE THREADED ?
//YES ,NODEJS IS SINGLE THREADED ONLY,BUT HANDLES CONCURRENCY USING NON-BLOCKING I/O...

//^ V8 ENGINE :--
// V8 IS GOOGLE JAVA SCRIPT ENGINE THAT CONVERTS JS INTO MACHINE CODE FOR FAST...

//^ NON-BLOCKING I/O :--
//IT ALLOWS OTHER OPERATIONS TO CONTINUE WHILE THE WAITING FOR I/O TASKS TO BE COMPLETE...


//^ SYNCHRONOUS EXECUTION :--
//IT BLOCKS THE NEXT OPERATION UNTILL THE CURRENT ONE FINISHES.....

//^ ASYNCHRONOUS EXECUTION :--
//IT ALLOWS TASKS TO RUN INDEPENDENTLY WITHOUT BLOCKING THE MAIN THREAD


//^ EVENT LOOP :--
// IT MANAGES ASYNCHRONOUS CALLBACKS AND EXECUTES THEM WHEN THE CALLSTACK IS EMPTY..


//^ LIBUV :---
// IT IS C LIBRARY THAT PROVIDES EVENT LOOP ANDN ASYNC I/O SUPPORT IN NODEJS..


//^ CALLBACK QUEUE :--
// IT STORES COMPLETED ASYNC CALLBACK  WAITING TO BE EXECUTED


//^ CALLSTACK :--
//IT STORES FUNCTION CALLS AND EXEXUTES THEM IN LIFO ORDER...


//^ MICROTASK QUEUE :--
//THIS WILL HAVE HIGHEST PRIORITY AND ALSO CAN SAY THIS IS MOST URGENT CALLBACKS WILL STORE ..

//^ WHAT ARE TYES OF MICROTASKS QUEUE :--
//THERE ARE TWO TYPES:-
//1.nextTick 2.promise


//^ process.nexTick ():--
// it executes  A CALLBACK BEFORE THE NEXT EVENT LOOP ITERATION BEGIN

//^ PRIORITY WISE - PHASES IN EVENT LOOP :--
/**
 * 5 PHASES:--
 * 1.MICROTASK QUEUE-->1.1 nextTick ,1.2.promise
 * 2.TIMER QUEUE(setTimeout,setInterval)
 * 3.I/O QUEUE(fs,dns,database)
 * 4.CHECK QUEUE(setImmediate)
 * 5.CLOSE QUEUE
 */

//* CODE EXECUTION :--

// const fs=require('fs')

// const readablestream=fs.createReadStream(__filename)

// readablestream.close()
// readablestream.on("close",()=>{
//     console.log('Close queue');
// })

// setImmediate(
//     ()=>{
//         console.log('Check queue ');
//     }
// )

// process.nextTick(
//             ()=>{
//                 console.log('nextTick  queue ');
//             }
// )
// Promise.resolve().then(
//             ()=>{
//                 console.log('Promise  queue ');
//             }
// )

// setTimeout(
//     ()=>{
//         console.log('Timer queue');
//     },0
// )

//^ setImmediate:---
//it executes a callback after the I/O PHASE  of the event loop....

//^ nodejs RUNTIME ARCHITECTURE :--
//IT CONISISTS OF V8 ENGINE,EVENT LOOP ,CALLBACK QUEUE,LIBUV THREAD POOL..


//^ MODULES IN NODEJS :---
//MODULES ARE REUSABLE BLOCK OF CODE THAT CAN BE IMPORTED AND EXPORTED..

//^ TYPES OF MODULES :--
/**
 * THREE TYPES OF MODULES :--
 * 1.USER DEFINED/LOCAL MODULES
 * 2.BUILT-IN / CORE MODULES
 * 3.THIRD PARTY MODUES
 */

//^ WHAT IS COMMON JS MODULES :---
//THESE ARE DEFALUT MODULES BY NODEJS ...
//WE USE require() to import and module.exports


//^ fs MODULE :--
//FS MODULE IS USED TO PERFORM FILE OPERATIONS LIKE READ,WRITE,UPDATE,RENAME,DELETE ALS FOR FOLDERS


//^ DIFFERENCE BETWEEN SYNC AND ASYNC FS METHODS:--
//SYNC METHODS BLOCK EXECUTION ,ASYNC METHODS DONT BLOCK EXECUTION....


//^ PATH MODULE :--
//IT PROVIDES UTILITIES TO WORK WITH FILE AND DIRECTORY PATHS..join()  vs resolve ()

//^ URL MODULE :--
//IT IS USED TO PARSE  AND MANIPULATE URL STRINGS

//^ OS MODULE :--
//IT PROVIIDES SYSTEM LEVEL INFORMATION LIKE CPU,MEMORY AND PLATFORM,,ETC



//^ BUFFERS :--
// BUFFERS HANDLE BINARY DATA DIRECTLY IN MEMORY FOR FILES AND NETWORK DATA...


//^ STREAMS :--
//STREAMS ARE  PROCCESSING DATA IN CHUNKS INSTEAD OF LOADING ENTIRELY AT ONCE...


//^ TYPES OF STREAMS :--
//READABLE,WRITABLE,DUPLEX,TRANSFORM


//^ EVENTEMITTER :---
// IT IS CLASS  USED TO CREATE AND HANDLE CUSTOM EVENTS


//^ HTTP MODULE :--
//IT IS USED TO CREATE SERVER AND HANDLLE THE REQUESTS AND RESPONSES..

//^ HTTP METHODS :--
//GET , POST ,PUT ,DELETE ,PATCH

//^ REFER QUERY -->


//^ ROUTING IN HTTP :--
//IT DIRECTS REQUESTS TO DIFFERENT RESPONSES BASED ON URL AND HTTP METHODS..

//^ NPM :--
//IT IS THE PACKAGE MANAGER FOR NODEJS WHERE WE CAN INSTALL PACAKAGES


//^ PACKAGE.JSON:--
//IT STORED METADATA,SCRIPTS,DEPENDENCIES


//^ WHAT IS DATABASE CONNECTIVITY IN NODEJS:---

//IT IS TO CONNECT AND INTERACT WITH DATABASES LIKE MONGODB,,REDIS,

//^ HOW NODEJS IS FAST ?
//BECAUSE OF V8 ENGINE AND NON-BLOCKING I/O


//^ WHAT IS SCALIBILITY IN NODEJS ?
//ABITILITY TO HANDLE INCREASING USERS EFFIECIENTLY USING ASYNC I/O 

//*=======ADVANCED LEVEL NODEJS================

//^ HOW NODEJS HANDLES CONCURRENCY ?
/**
 * IT USES :--
 * EVENT LOOP
 * ASYNC CALLBACKS
 * WORKER THREAD POOL
 */


//^ CLUSTER MODULE :---
/**
 * IT IS USED TO UTILIZE MULTIPLE CPU CORES..
 * CREATES MULTIPLE NODE PROCESSES
 */


//^ WORKER THREADS ?
/**
 * IT ENABLES MULTI THREADING
 * IT IS USED CPU NTENSIVE TASKS
 */


//^ BACK PRESSURE ?
/**
 * WHEN WRITABLE STREAM CANNOT HAMDLE INCOMING DATA...
 * SOLVED USING .pipe() AND STREAM CONTROL
 */



//^ MEMORY LEAK IN NODEJS ?
/**
 * UNREALEASED REFERENCES:
 * IT CAUSES GLOBAL VARIABLES
 * EVENT LISTENERS NOT REMOVED
 * CLOSURES
 */



//^  HOW DO YOU DEBUG NODEJS ?
/**
 * CONSOLE.LOG
 * DEBUGGER KEYWORD
 * NODE INSPECTOR
 * CHROME DEV TOOLS
 */



//!=======MONGODB ===================
//^ WHAT IS MONGODB ?
//MONGODB IS NOSQL,DOCUMENT BASED DATABASE

//^ COLLECTION ?
//IT STORES MULTIPLE DOCUMENTS..

//^ DOCUMENTS ?
//IT IS JSON LIKE DATA STRUCTURE..

//^ SQL AND MONGODB ?
//SQL USES TABLES(ORM),MONGODB USES COLLECTION(ODM)

//^ SCHEMA IN MONGODB ?
//SCHEMA DEFINES  STRUCTURE OF DOCUMENTS...

//^ MONGOOSE ?
// MONGOOSE IS ODM FOR MONGODB.

//^ WHY MONGOOSE ?
// IT PROVIDES SCHEMA VALIDATION AND QUERY HELPERS.....

//^ CRUD IN MONGODB ..?
//CREATE,READ,UPDATE,DELETE,REPLACE OPERATIONS...

//^ FIND():--
//USED TO FETCH MULTIPLE DOCUMENTS EVEN IF IT HAS FILTER CONDITION OR NOT..

//^ FINDoNE():--
//USED TO FETCH SINGLE DOCUMENT EVEN IF IT HAS FITER ..IF THERE IS NO FILTER ,IT WILL DISPLAY FIRST DOCUMENT...

//^ INSERTONE():--
//INSERT ONE DOCUMENT  FOR COLLECTION....

//^ IMSERTMANY :--
//INSERT ALL DOCUMENTS FOR A COLLECTION..


//^ UPDATEONE():--
//IF THERE FILTER CONDITION FOR THOSE ONLY IT WIL UPDATE...IDF THERE IS NO FILTER CONDITION-->IT WILL UPDATE FIRST DOC


//^ UPDATEMAY :-- ||SIMILAR TO THIS UPDATEONE BUT IN THIS INSERTMANY UPDATES MULTIPLE DOCUMNETS..

//^ DELETEONE :--USED TO DELETE DOCUMNETS
//^ DELETEMANY :--UDE TO DELETE ALL DOCUMENTS


//^ REPLACEONE :--
//USED TO REPLACE ENTIRE DOCUMENTS ,ITS OPPOSITE TO UPDATE..

//^ INDEXING :--
//IMPROVES QUERY PERFOMANCE


//^ TYPES OF INDEXES :--
/**
 * DEFAULT INDEX
 * SINGLE INDEX
 * COMPOUND INDEX
 * MULTI KEY INDEX
 * UNIQUE INDEX
 */


//^ UNIQUE INDEX :--
//PREVEENTS DUPLICATES VALUES IN FIELD..

//^ AGGREGATIONS:--
//AGGREGATION IS COMPUTED RESULT PROJECT,MATCH,GROUPING,FILTER GROUPS .SORT,SKIP,,,,ALL WILL BE DONE IN PIPELINE-->STAGE BY STAGE EXECUTION...

//^ PROJECTION :---
//SELECTING SPECIFIC FIELDS FROM DOCUMENTS....


//^ PAGINATION :---
//FTECHING DATA IN LIMITED CHUNKS...

//^ TRANSACTION :---
//ENSURING ATOMIC OPERATIONS...

//^ ATOMIC OPERATION :---
//OPERATIONS TYHAT COMPLETELY FULLY OR NOT AT ALL..


//^ SOFT DELETE :--
//MARKING AS DELETED WITHOUT REMOVING IT..

//^ MONGODB NATIVE DRIVER:---
//OFFICIAL DRIVER TO INTERACT WITH MONGODB...

//^ WHY MONGODB IS SCALABLE :--
//IT SUPPORTS HORIZONTAL SCALING USING SHARDING

//^ SHARDING :--
// IT WILL SPLIT THE DATA ACCOSS MULTIPLE SERVERS
//WE USE SHARD(PART) KEYS

//^ REPLICATION :--
//IT WILL CREATES COPY OF DATA ACROSS DIFFERENT SERVERS...
// WE USE REPLICA SETS...


//^ WHO INTRODUCED MONGODB ALSO IN WHICH YEAR :---
// DWIGHT MERRIMEN,ELIOT HOROWITZ,KEVIN P RYAN INTRODUCED IN 2007 BUT OFFICIAL VERSION CAME IN 2009



//^ CAP THEOREM :--
/**
 * MONGODB GURANTEES TWO AMONG THREE :--
 * BY DEFALUT IT PREFERS CP ,,,IT CAN BE CONFIGURED DEPENDING UPON UR REQUIREMENTS...
 */


//^ CAPPED COLLECTION :---
//WE CAN FIX THE SIZE (STORAGE)
// , NUMBER OF DOCUMENTS ....


//^ CURSORS :--
//IT IS RESULT OF QUERY WHICH ACTS LIKE POINTER.
//BY DEFALU WE CAN GET ONLY 20 DOC IN BATCH WISE..



//^ LIST ANY METHODS OF CURSORS :--
//SKIP,LIMIT,SIZE,COUNT,.....


//^ CAN WE DESIGN A CHEMA IN MONGODB INCLUDING RULES ...
//YES ,JSONSCHEMA AND $ VALIDATOR


//^ $lookup :--
//we can fetch documents from other collections tooo...


//^ Array update operators :--
//push,pull,pullAll,pop,addtoset all these oprators specifically will work for only array fields

//^ Bulk operation:---
//bulkWrite() --> all the crud opertion can be executrs in single time ....except insertMany()